dist: bionic
language: perl
os: linux
if: tag IS blank AND env(GITHUB_OAUTH_TOKEN) IS present AND type IN (push, pull_request)
branches:
  only:
  - master
cache:
  directories:
  - perl_modules
before_install:
- cpanm local::lib
- eval "$(perl -Mlocal::lib=${PWD}/perl_modules)"
- cpanm --notest Dist::Zilla
addons:
  apt:
    packages:
    - git
    - wget
    - file
    - build-essential
    - libssl-dev
    - libexpat1-dev
    - cpanminus
    - libz-dev
    - unzip
    - liblzma-dev
    - zlib1g-dev 
    - libncurses5-dev
    - libbz2-dev
perl:
- "5.30"
install:
- mkdir dependencies
- export SAMTOOLS_VERSION=0.1.19
- export SUBREAD_VERSION=1.4.5-p1
- export TABIX_VERSION=0.2.5
- ./install_dependencies.sh $(pwd)/dependencies ${SAMTOOLS_VERSION} ${TABIX_VERSION} ${SUBREAD_VERSION}
- export SAMTOOLS=/opt/samtools-${SAMTOOLS_VERSION}
- export PATH=$(pwd)/dependencies/samtools-${SAMTOOLS_VERSION}:$(pwd)/dependencies/tabix-${TABIX_VERSION}:$(pwd)/dependencies/subread-${SUBREAD_VERSION}-Linux-x86_64/bin:$(pwd)/dependencies/subread-${SUBREAD_VERSION}-Linux-x86_64/bin/utilities:$PATH
- export PERL_INLINE_DIRECTORY=$(pwd)/Inline
- mkdir ${PERL_INLINE_DIRECTORY}
- git config --local user.name "Pathogen Informatics CI"
- git config --local user.email "pathdev@sanger.ac.uk"
- export UUID=$(cat /proc/sys/kernel/random/uuid)
- git checkout -b $UUID
- export TIMESTAMP_VERSION=$(date -u '+%Y.%m.%d.%H.%M.%S.%3N')
- export TRAVIS_TAG=$(if [ "$TRAVIS_BRANCH" == "master" ]; then echo "v${TIMESTAMP_VERSION}"; else echo "$TRAVIS_BRANCH-${TIMESTAMP_VERSION}"; fi)
- sed -i 's:^version = .*$:version = '"$TIMESTAMP_VERSION"':g' dist.ini
- git commit -am "Updated the version number to $TIMESTAMP_VERSION"
- git tag $TRAVIS_TAG
- if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then git push -q "https://${GITHUB_OAUTH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}" $TRAVIS_TAG; fi
- dzil authordeps --missing | cpanm --notest 
- dzil listdeps --missing | cpanm --notest
script:
- dzil build
- dzil test
deploy:
  provider: releases
  api_key: "$GITHUB_OAUTH_TOKEN"
  file_glob: true
  file: "*.tar.gz"
  skip_cleanup: true
